from flask import Flask, jsonify, request, url_for
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import Input,Dropout,GlobalAveragePooling2D,BatchNormalization,Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from tensorflow.keras.applications import EfficientNetB5
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from werkzeug.utils import secure_filename
import numpy as np
import pandas as pd
import numpy as np
import re
import os
 
# https://www.tutorialspoint.com/flask
import flask

PEOPLE_FOLDER = 'static'
app = Flask(__name__)


app.config['UPLOAD_FOLDER'] = PEOPLE_FOLDER


model = EfficientNetB5(include_top=False, input_shape=(224, 224, 3), weights="imagenet")             #https://www.tensorflow.org/api_docs/python/tf/keras/applications/efficientnet/EfficientNetB5
model.trainable = True
input_layer = model.output    #Get this method from classrom query resolution, https://www.tensorflow.org/api_docs/python/tf/keras/Model

layer1 = GlobalAveragePooling2D()(input_layer)    

layer2 = BatchNormalization()(layer1)

layer3 = Dropout(0.2)(layer2)

#output layer
output = Dense(38, activation="softmax")(layer3)

# creating the final model 
model = Model(inputs=model.input, outputs = output)   #https://www.tensorflow.org/api_docs/python/tf/keras/Model
# compile the model 
optimizer = Adam(beta_1 = 0.9, beta_2 = 0.999, decay = 0.0,learning_rate=0.001)

model.compile(loss = "categorical_crossentropy", optimizer = optimizer, metrics=["accuracy"])

model.load_weights('Model_1\weight.hdf5')

###################################################

def predict(img_bytes,model):    
    img = image.load_img(img_bytes, grayscale=False, target_size=(224,224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = np.array(x, 'float32')
    datagen = ImageDataGenerator(zoom_range = 0.2,horizontal_flip = True,rotation_range=15,vertical_flip=True,brightness_range=[0.5, 1.5])
    img = datagen.flow(x, batch_size=1)
    pred = model.predict(img)
    pred2 = model2.predict(img)
    
    k = 0
    while pred[0][np.argmax(pred)] <0.99:
        if k == 15:
            break
        else:
            img = datagen.flow(x, batch_size=1)
            pred = model.predict(img)
        k += 1
    if pred[0][np.argmax(pred)] <0.96:
        pred = 38
        return pred
    else:
        pred = np.argmax(pred)
        return pred

###################################################

@app.route('/')
def index():
    return flask.render_template('index.html')
    
@app.route('/predict', methods=['POST'])

def upload_file():
    file = [i for i in os.scandir('static')]
    if len(file) > 0:
        for i in file:
            os.remove(i.path)
    f = request.files['file']
    # Save the file to ./uploads
    full_filename = os.path.join(app.config['UPLOAD_FOLDER'], secure_filename(f.filename))
    file_path= os.path.join('static', secure_filename(f.filename))
    f.save(file_path)
    
 
    pred = predict(file_path,model)
    label = ['Apple___Apple_scab','Apple___Black_rot','Apple___Cedar_apple_rust','Apple___healthy','Blueberry___healthy','Cherry_(including_sour)___Powdery_mildew','Cherry_(including_sour)___healthy','Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot','Corn_(maize)___Common_rust_','Corn_(maize)___Northern_Leaf_Blight','Corn_(maize)___healthy','Grape___Black_rot','Grape___Esca_(Black_Measles)','Grape___Leaf_blight_(Isariopsis_Leaf_Spot)','Grape___healthy','Orange___Haunglongbing_(Citrus_greening)','Peach___Bacterial_spot','Peach___healthy','Pepper_bell___Bacterial_spot','Pepper_bell___healthy','Potato___Early_blight','Potato___Late_blight','Potato___healthy','Raspberry___healthy','Soybean___healthy','Squash___Powdery_mildew','Strawberry___Leaf_scorch','Strawberry___healthy','Tomato___Bacterial_spot','Tomato___Early_blight','Tomato___Late_blight','Tomato___Leaf_Mold','Tomato___Septoria_leaf_spot','Tomato___Spider_mites Two-spotted_spider_mite','Tomato___Target_Spot','Tomato___Tomato_Yellow_Leaf_Curl_Virus','Tomato___Tomato_mosaic_virus','Tomato___healthy','Not in our predict list']
    #https://plantix.net/en/library/plant-diseases
    fertilizer = {'Apple___Apple_scab': ["What cause it: Apple scab is as disease caused by the fungus Venturia inaequalis. It survives the winter mainly on infected leaves on the ground but also on bud scales or lesions on wood.At the onset of spring, the fungus resumes frowth and starts to produce spores, which are later discharged and dispersed over long distances by wind.","Organic Control: If disease levels were high the previous season, liquid copper fungicides can be sprayed to impede the fungal growth on the tree during the winter season. Sulfur sprays are only partially effective against apple scrab. However, solutions conatining sulfur and pyrethrins are available for organic control of the disease during the growing season.","Chemical Control: Once scab has been detected, fungicides based on difenoconazole, myclobutanil or sulphur can be used to control the development of the fungus. Ensure scab fungicides from different chemical groups are used to avoid the development of resistance."],
             'Apple___Black_rot': ["What cause it: Disease is caused by a virus of the Trichovirus group, and it is one of the most economically important viruses affecting stone and prome fruits. The disease is transmitted through vegetative propagation, grafting and top working. This virus can have a devastating effect on apple growth and productivity. The virus can have a devastating effect on apple growth and productivity by up to 30%.","Organic Control: To this day, we are not aware of any biological control method available against this disease. If you know of any successful method to reduce the incidence or he gravity of the symptoms, please contact us.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available, We are not aware of any chemical control method against this disease.If you know of any successful method to reduce the incidence or he gravity of the symptoms, please contact us."],
             'Apple___Cedar_apple_rust': ["What cause it: The virus has no natural vector. Infected branches transmit the virus when used as slips for grafting. The virus can also be transmitted through the roots. Systoms are more pronounced in years with moderate springtime temperatures.","Organic Control: This virus cannot be cured. The affected tree should be removed to prevent spreading to other trees.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. There is no chemical treatment of this viral disease."],
             'Apple___healthy': "Healthy Plant",
             'Blueberry___healthy': "Healthy Plant",
             'Cherry_(including_sour)___Powdery_mildew': ["What cause it: Fungal spores overwinter inside leaf buds and other plant debris. Wind, water, and insects transmit the spores to nearby plants. Even though it is a fungus, powdery mildew can develop rather normally in dry conditions. It survives at temperatures between 10-20 degree celsius, but optimal conditions are found at 30 degree celsius. In contrast to downy mildew, small amounts of rainfall and regular morning dew accelerate the spreading of powdery mildew.","Organic Control: Foliar sprays based on sulfur,neem oil,kaolin or ascorbic acid can prevent severe infection.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. In view of the number of crops that are susceptible to powdery mildew, it is difficult to recommend any particular chemical treatment. Fungicides based on wettable sulphur(3g/L),hexaconazole,myclobutanil(all 2ML/L) seem to control the growth of the fungus in some crops."],
             'Cherry_(including_sour)___healthy': "Healthy Plant",
             'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': ["What cause it: It was caused by fungus Bolumeriella jaapii, which can affect, besides corn,plum and apricot trees. The fungus overwinters on fallen leaves on the orchard floor. In spring, when temperatures are above 6 degree celsius, the fungus germinates and produces spores that are spread by wind or rain. Leaves remain susceptible throughout the growing season. The infection cycle can be repeated several time during a single season, depending on environmental conditions, pariculary leaf wetness.","Organic Control: No biological control solution seems to be available against this disease. Please contact us if you know of any.Treatments with organic fungicides include formulations containing copper salts such as copper hydroxide or copper sulfate may provide some protection against leaf spot infection.Fungicides work best if combined with sanitation of the field.","Chemical Control: Always consider an integrated approach with preventive measures and biological treatments if available.Preventive measures are essential to control the disease but ultimately fungicides are required to maximize yield and quality."],
             'Corn_(maize)___Common_rust_': ["What cause it: 98% relative humidity and cool nights followed by warm days with temperatures between 20 degree celsius and 25 degree celsius favour common rust. Continuous leaf wetness (nine hours or more) also supports the spread of the disease. Under favorable conditions the infection cycle of Common Rust is less than 14 days long. Plants aged 2-6 month are most susceptible to common Rust.","Organic Control: Orry, we don't know of any alternative treatment against Puccinia melanocephala. Please get in touch with us in case you know of something that might help to fight this disease.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. A treatment with fungicides can be economically unfavorable and not practical."],
             'Corn_(maize)___Northern_Leaf_Blight': ["What cause it: The fungus overwinters in the soil or on plant debris. Rainfall, night dew, high humidity and moderate temperatures favor the dispersion of the fungus. Carried by wind or rain splashes it first spreads from the soil onto the lower leaves of young maize plants. Rainy conditions and poor field practices favor its spread to other plants and within fields. Optimal temperatures for infection are in the range of 18-27 degree celsius during the growing season.","Organic Control: Bio-fungicides based on Trichoderma harzianum, or Bacillus subtilis can be applied at different stages to decrease the risk of infection. Application of sulfur solution is also effective.","Chemical Control: An integrated approach with preventive measures together with careful cultural practices is recommended. An early preventative fungicide application can be an effective way of controlling the disease. Otherwise, fungicides can be applied when the symptoms are visible on lower canopy to protect the upper leaves and ears. Apply sprays based on azoxystrobin, picoxystrobin, mancozeb, pyraclostrobin, propiconazole, tetraconazole apply products based on picoxystrobin + cyproconazole, pyraclostrobin + metconazole, propiconazole + azoxystrobin, prothioconazole + trifloxystrobin. Seed treatments are not recommended."],
             'Corn_(maize)___healthy': "Healthy Plant",
             'Grape___Black_rot': ["What cause it: The symptoms are caused by the soil-borne bacterium Xanthomonas campestris, which survives in infected crop debris or seeds for up to 2 years, or on weeds of the Brassica family for longer periods. I affects a large number of vegetables in the cabbage family(including broccoli,cauliflower,turnip,radish and kohlrabo). The bacterium spreads to healthy plants via water splashes and enters the tissues through different paths,among other injuries.Once a plant infected it spreads quickly to other cabbages.","Organic Control: A hot water bath for 30 minutes at 50 degree celsius is the recommended treatment to sterilize the seeding material. This is not 100 percent effective against black rot but reduces the incident of the disease considerably. The drawback is that it might lower the germination rate.","Chemical Control: Always consider an integrated approach with preventive measures and available biological treatments. Seed treatments with hot water are very effective in blocking the contamination of fields. Foliar treatments with copper based fungicides every 7-10 days can also slow the spread of the disease. Unfortunately, these treatments can cause black spots to develop on the outer leaves of the cabbage."],
             'Grape___Esca_(Black_Measles)': ["What Cause it: The symptoms are caused by the fungus Phakopsora vitis. The fungal spores survive on plant debris and alternate hosts and are dispersed via wind. The pathogen of rust is developes in the spots which are present on the lower surface of leaf in the form of orange colored granules. Yellowish orange masses of uredinospores are produced on the lower leaf side, with dark necrotic spots on the upper surface. Temperatures above 20 degree celsius and moist weather conditions favor the disease development. The spores can easily be transported by wind and air currents.","Organic Control: Apply a foliar with sulfur containing fungicide. Avoid spraying during rainy weather, to ensure the fungicide can act against the pathogen.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Use fungicides containing Bordeaux misture, Captafol, difolatan, propiconazole, tebuconazole or azoxystrobin, which are said to significantly reduce the pathogen incident. Rust can be controlled in vineyards by applying 3-4 sprays of Baycor(0.1%) at fortnight intervals during the subsequent growing seasons."],
             'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': ["What Cause it: The bacteria prefers hight humidity and high temperatures. The primary transmission takes place through soil and diseased setts, while the secondary transmission happens through air, rain and soil.","Organic Control: Unfortunely, no effective biological control methods are available at this time.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available, To avoid primary infection treatment of the seeds with the appropriate fungicide for 15 to 20 minutes could be conducted."],
             'Grape___healthy': "Healthy Plant",
             'Orange___Haunglongbing_(Citrus_greening)': ["What Cause it: The symptoms of huanglongbing (HLB) are caused by the bacterium Candidatus Liberibacter asiaticus. It is transmitted persistently by two psyllid vectors that are omnipresent in the citrus grooves, Diaphorina citri and Trioza erytreae. HLB can be acquired by both nymphs and adults, which can maintain and transmit the disease throughout their 3- to 4-month lifespan. Huanglongbing is systemic and has an incubation period of three months to several years before symptoms are visible. The disease can also be spread through grafting, even though with variable transmission rates. Seed transmission may also be possible. Other pathologies or disorders also show such a mottling of the leaves. It is thus recommended to send samples of tissues for analysis in laboratories to ascertain the cause.","Organic Control: Sorry, we don't know of any biological treatment against this disease. Please get in touch with us in case you know of something that might help to fight this disease. We are looking forward hearing from you.","Chemical Control: Always consider an integrated approach with preventive measures and biological treatments if available. An appropriate use of insecticides has resulted in good control of the psyllid vectors and thus a limited spread of the disease. Injection of the antibiotic tetracycline into the trunk of the trees may result in a partial recovery but has to be repeated often to show effect. Tetracycline is phytotoxic and may have adverse effects on the environment. For these reasons, its use has decreased in recent years."],
             'Peach___Bacterial_spot': ["What Cause it: Bacterial spot occurs worldwide and is one of the most devastating diseases on pepper and tomato crops grown in warm, moist environments. The pathogen can survive in association with seeds, either externally or internally as well as on specific weeds and later spreads through rain or overhead irrigation. It enters the plant through leaf pores and wounds. Optimum temperatures range from 25 to 30°C. Once the crop is infected, the disease is very difficult to control and can lead to total crop losses.","Organic Control: Bacterial Spot is very difficult and expensive to treat. If the disease occurs early in the season, consider destroying the entire crop. Copper-containing bactericides provide a protective cover on foliage and fruit. Bacterial viruses (bacteriophages) that specifically kill the bacteria are available. Submerge seeds for one minute in 1.3% sodium hypochlorite or in hot water (50°C) for 25 minutes.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Copper-containing bactericides can be used as a protectant and give partial disease control. Application at the first sign of disease and then at 10- to 14-day intervals when warm, moist conditions prevail. The active ingredients copper and mancozeb give a better protection."],
             'Peach___healthy': "Healthy Plant",
             'Pepper_bell___Bacterial_spot': ["What Cause it: Bacterial spot occurs worldwide and is one of the most devastating diseases on pepper and tomato crops grown in warm, moist environments. The pathogen can survive in association with seeds, either externally or internally as well as on specific weeds and later spreads through rain or overhead irrigation. It enters the plant through leaf pores and wounds. Optimum temperatures range from 25 to 30°C. Once the crop is infected, the disease is very difficult to control and can lead to total crop losses.","Organic Control: Bacterial Spot is very difficult and expensive to treat. If the disease occurs early in the season, consider destroying the entire crop. Copper-containing bactericides provide a protective cover on foliage and fruit. Bacterial viruses (bacteriophages) that specifically kill the bacteria are available. Submerge seeds for one minute in 1.3% sodium hypochlorite or in hot water (50°C) for 25 minutes.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Copper-containing bactericides can be used as a protectant and give partial disease control. Application at the first sign of disease and then at 10- to 14-day intervals when warm, moist conditions prevail. The active ingredients copper and mancozeb give a better protection."],
             'Pepper_bell___healthy': "Healthy Plant",
             'Potato___Early_blight': ["What Cause it: Symptoms are caused by Alternaria solani, a fungus that overwinters on infected crop debris in soil or on alternative hosts. Purchased seeds or seedlings may also be already contaminated. Lower leaves often get infected when in contact with contaminated soil. Warm temperatures (24- 29°C) and high humidity (90%) favor development of the disease. A long wet period (or alternating wet/dry weather) enhances the production of spores, which may be spread via wind, splashing rain or overhead irrigation. Tubers harvested green or in wet conditions are particularly susceptible to an infection. It often strikes after a period of heavy rainfall and is particularly destructive in tropical and subtropical areas.","Organic Control: Application of products based on Bacillus subtilis or copper-based fungicides registered as organic can treat this disease.","Chemical Control: Always consider an integrated approach with preventive measures and biological treatments if available. There are numerous fungicides on the market for controlling early blight. Fungicides based on or combinations of azoxystrobin, pyraclostrobin, difenoconazole, boscalid, chlorothalonil, fenamidone, maneb, mancozeb, trifloxystrobin, and ziram can be used. Rotation of different chemical compounds is recommended. Apply treatments in a timely manner, taking into account weather conditions. Check carefully the preharvest interval at which you can harvest safely after the application of these products."],
             'Potato___Late_blight': ["What Cause it: The risk of infection is highest in midsummer. The fungus enters the plant via wounds and rips in the skin. Temperature and moisture are the most important environmental factors affecting the development of the disease. Late blight fungi grow best in high relative humidities (around 90%) and in temperature ranges of 18 to 26°C. Warm and dry summer weather can bring the spread of the disease to a halt.","Organic Control: At this point, there is no biological control of known efficacy against late blight. To avoid spreading, remove and destroy plants around the infected spot immediately and do not compost infected plant material.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Use fungicide sprays based mandipropamid, on chlorothalonil, fluazinam, mancozeb to combat late blight. Fungicides are generally needed only if the disease appears during a time of year when rain is likely or overhead irrigation is practiced."],
             'Potato___healthy': "Healthy Plant",
             'Raspberry___healthy': "Healthy Plant",
             'Soybean___healthy': "Healthy Plant",
             'Squash___Powdery_mildew': ["What Cause it: Fungal spores overwinter inside leaf buds and other plant debris. Wind, water, and insects transmit the spores to nearby plants. Even though it is a fungus, powdery mildew can develop rather normally in dry conditions. It survives at temperatures between 10-20 degree celsius, but optimal conditions are found at 30 degree celsius. In contrast to downy mildew, small amounts of rainfall and regular morning dew accelerate the spreading of powdery mildew.","Organic Control: Foliar sprays based on sulfur,neem oil,kaolin or ascorbic acid can prevent severe infection.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. In view of the number of crops that are susceptible to powdery mildew, it is difficult to recommend any particular chemical treatment. Fungicides based on wettable sulphur(3g/L),hexaconazole,myclobutanil(all 2ML/L) seem to control the growth of the fungus in some crops."],
             'Strawberry___Leaf_scorch': ["What Cause it: The fungus P. tetraspora, which causes angular leaf scorch survives the winter in infected leaves on the vineyard floor. Therefore, foliage free dormant cuttings do not provide a pathway for these fungi. During wet weather in spring fungal spores are released from these fallen leaves and spread by wind and waty splashes to new leaves and flower stems. There is normally only one cycle of infection in spring from the overwintering fungus on the decaying leaves. Occasionally after several consecutive days of constant rainfall, spores may be formed on the dead tissue of infected leaves still attached to the vine. These spores can cause secondary infections any time during the growing season if moist conditions persist. This explains why the disease may seem absent in most years but can be severe in years with prolonged rainy weather.","Organic Control: No biological treatments are available against this disease. The best way to avoid heavy losses is to remove severely infected twigs or entire plants and destroy them by deep- burying or burning in distance to the orchard. Good weeding and sanitation programs are also recommended.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. The disease can be controlled by applying fungicides containing mancozeb before rainy weather. Applications should begin at early shoot growth, and protection should be maintained through fruit set, even more so during rainy weather."],
             'Strawberry___healthy': "Healthy Plant",
             'Tomato___Bacterial_spot': ["What Cause it: Bacterial spot occurs worldwide and is one of the most devastating diseases on pepper and tomato crops grown in warm, moist environments. The pathogen can survive in association with seeds, either externally or internally as well as on specific weeds and later spreads through rain or overhead irrigation. It enters the plant through leaf pores and wounds. Optimum temperatures range from 25 to 30°C. Once the crop is infected, the disease is very difficult to control and can lead to total crop losses.","Organic Control: Bacterial Spot is very difficult and expensive to treat. If the disease occurs early in the season, consider destroying the entire crop. Copper-containing bactericides provide a protective cover on foliage and fruit. Bacterial viruses (bacteriophages) that specifically kill the bacteria are available. Submerge seeds for one minute in 1.3% sodium hypochlorite or in hot water (50°C) for 25 minutes.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Copper-containing bactericides can be used as a protectant and give partial disease control. Application at the first sign of disease and then at 10- to 14-day intervals when warm, moist conditions prevail. The active ingredients copper and mancozeb give a better protection."],
             'Tomato___Early_blight': ["What Cause it: Symptoms are caused by Alternaria solani, a fungus that overwinters on infected crop debris in soil or on alternative hosts. Purchased seeds or seedlings may also be already contaminated. Lower leaves often get infected when in contact with contaminated soil. Warm temperatures (24- 29°C) and high humidity (90%) favor development of the disease. A long wet period (or alternating wet/dry weather) enhances the production of spores, which may be spread via wind, splashing rain or overhead irrigation. Tubers harvested green or in wet conditions are particularly susceptible to an infection. It often strikes after a period of heavy rainfall and is particularly destructive in tropical and subtropical areas.","Organic Control: Application of products based on Bacillus subtilis or copper-based fungicides registered as organic can treat this disease.","Chemical Control: Always consider an integrated approach with preventive measures and biological treatments if available. There are numerous fungicides on the market for controlling early blight. Fungicides based on or combinations of azoxystrobin, pyraclostrobin, difenoconazole, boscalid, chlorothalonil, fenamidone, maneb, mancozeb, trifloxystrobin, and ziram can be used. Rotation of different chemical compounds is recommended. Apply treatments in a timely manner, taking into account weather conditions. Check carefully the preharvest interval at which you can harvest safely after the application of these products."],
             'Tomato___Late_blight': ["What Cause it: The risk of infection is highest in midsummer. The fungus enters the plant via wounds and rips in the skin. Temperature and moisture are the most important environmental factors affecting the development of the disease. Late blight fungi grow best in high relative humidities (around 90%) and in temperature ranges of 18 to 26°C. Warm and dry summer weather can bring the spread of the disease to a halt.","Organic Control: At this point, there is no biological control of known efficacy against late blight. To avoid spreading, remove and destroy plants around the infected spot immediately and do not compost infected plant material.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Use fungicide sprays based on mandipropamid, chlorothalonil, fluazinam, mancozeb to combat late blight. Fungicides are generally needed only if the disease appears during a time of year when rain is likely or overhead irrigation is practiced."],
             'Tomato___Leaf_Mold': ["What Cause it: The symptoms are caused by the fungus Mycovellosiella fulva, whose spores can survive without a host for 6 months to a year at room temperature (non-obligate). Prolonged leaf moisture and humidities above 85% favor the germination of spores. The temperature must be between 4° to 34 °C for spores to germinate, with an optimum temperature at 24- 26°C. Dry conditions and the absence of free water on leaves impair germination. The symptoms usually start to appear 10 days after inoculation with the development of spots on both sides of the leaf blade. On the underside, a large number of spore-producing structures are formed and these spores are easily spread from plant to plant by the wind and water splashing, but also on tools, clothing of workers and insects. The pathogen usually infects the leaves by penetrating through stomata in a high humidity level.","Organic Control: Seed treatment with hot water (25 minutes at 122 °F or 50 °C) is recommended to avoid the pathogen on seeds. The fungi Acremonium strictum, Dicyma pulvinata, Trichoderma harzianum or T. viride and Trichothecium roseum are antagonistic to M. fulva and could be used to reduce its spread. In greenhouse trials the growth of M. fulva on tomatoes was inhibited by A. strictum, Trichoderma viride strain 3 and T. roseum by 53, 66 and 84% respectively. In small arms, apple-cider, garlic or milk sprays and vinegar mix can be used to treat the mold.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Applications should be made prior to infection when environmental conditions are optimal for the development of the disease. Recommended compounds in field use are chlorothalonil, maneb, mancozeb and copper formulations. For greenhouses, difenoconazole, mandipropamid, cymoxanil, famoxadone and cyprodinil are recommended."],
             'Tomato___Septoria_leaf_spot': ["What Cause it: The symptoms are caused by the fungus Mycosphaerella fragariae, which overwinter on infected leaf debris on the soil. During the spring, they resume growth and start to produce spores that are spread to the lower leaves of the neighboring plants. Spores that land onto the leaf lamina form germ tubes which penetrate through natural openings on upper and lower surfaces of leaves. As it grows, the fungus produces clusters of new spores that are carried to new leaves by rain splashes and wind. Human or machinery activity in the field can also be a source of contamination. The fruits are generally not directly affected, but the loss of foliage can reduce their quality and the yield. Disease development is favored by cool daytime temperatures (around 25 °C) and cold nighttime temperatures, high relative humidity, and prolonged leaf wetness. Bad cultural practices, such as short spacing between plants, can also increases the risk of infection.","Organic Control: Solutions containing the bacterium Bacillus cereus and the yeast Saccharomyces boulardii were used with the same efficiency as fungicides for disease control in laboratory tests. However, these products still need to be tested in large field experiments.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. This disease is hard to control because plants can start to experience the effect of the disease prior to showing any symptoms. Fungicides based on chlorothalonil, myclobutanil or triflumizole can be used to control common leaf spot disease on strawberries after appearance of first symptoms. Treatments should be done early in the spring or immediately after renovation and it is recommended to spray at intervals of about 2 weeks."],
             'Tomato___Spider_mites Two-spotted_spider_mite': ["What Cause it: Damage is caused by spider mites from the genus Tetranychus, mainly T. urticae and T. cinnabarinus. The adult female is 0.6 mm long, pale green with two darker patches on its oval body, and long hairs on the back. Overwintering females are reddish. In spring, the females lay globular and translucent eggs on the underside of the leaves. The nymphs are pale green with darker markings on the dorsal side. The mites protect themselves with a cocoon on the underside of the leaf blades. The spider mite thrives in dry and hot climates and will produce up to 7 generations in one year in these conditions. There is a wide range of alternative hosts, including weeds.","Organic Control: In case of minor infestation, simply wash off the mites and remove the affected leaves. Use preparations based on rapeseed, basil, soybean and neem oils to spray leaves thoroughly and reduce populations of T. urticae. Also try garlic tea, nettle slurry or insecticidal soap solutions to control the population. In fields, employ host-specific biological control with predatory mites (for example Phytoseiulus persimilis) or the biological pesticide Bacillus thuringiensis. A second spray treatment application 2 to 3 days after the initial treatment is necessary.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments if available. Spider mites are very difficult to control with acaricides because most populations develop resistance to different chemicals after a few years of use. Choose chemical control agents carefully so that they do not disrupt the population of predators. Fungicides based on wettable sulfur (3 g/l), spiromesifen (1 ml/l), dicofol (5 ml/l) or abamectin can be used for example (dilution in water). A second spray treatment application 2 to 3 days after the initial treatment is necessary."],
             'Tomato___Target_Spot': ["What Cause it: Tomato spotted wilt virus (TSWV) is transmitted by various species of thrips, including the western flower thrips (Frankliniella occidentalis), the onion thrips (Thrips tabaci) and the chili thrips (Scirtothrips dorsalis). TSWV is also active in the thrips vector and can transmit it persistently. Nymphs that acquire the virus by feeding on infected plants will retain the ability to transmit it for the remainder of their lives. However, TSWV cannot be passed from infected females to the eggs. The virus has a very wide host range, including tomato, pepper, potato, tobacco, lettuce, and many other plants.","Organic Control: Some predatory mites feed on larvae or pupae of thrips and are commercially available. For varieties that attack the leaves and not the flowers, try neem oil or spinosad, especially on the undersides of the leaves. Spinosad application is very effective but can be toxic to certain natural enemies (e.g., predatory mites, syrphid fly larvae, bees) and should be avoided during flowering time. In case of flower thrips infestation, some predatory mites or green lacewing larvae could be used. A combination of garlic extracts with some insecticides also seem to work well.","Chemical Control: Always consider an integrated approach of preventive measures together with biological treatments if available. Due to the high reproductive rates and their life cycles, thrips have developed resistance to different classes of pesticides. Effective contact insecticides include azadirachtin or pyrethroids, which in many products are combined with piperonyl butoxide to enhance their effect."],
             'Tomato___Tomato_Yellow_Leaf_Curl_Virus': ["What Cause it: TYLCV is not seed-borne and is not transmitted mechanically. It is spread by whiteflies of the Bemisia tabaci species. These whiteflies feed on the lower leaf surface of a number of plants and are attracted by young tender plants. The whole infection cycle can take place in about 24 hours and is favored by dry weather with high temperatures.","Organic Control: There is no treatment against TYLCV. Control the whitefly population to avoid the infection with the virus.","Chemical Control: Once infected with the virus, there are no treatments against the infection. Control the whitefly population to avoid the infection with the virus. Insecticides of the family of the pyrethroids used as soil drenches or spray during the seedling stage can reduce the population of whiteflies. However, their extensive use might promote resistance development in whitefly populations."],
             'Tomato___Tomato_mosaic_virus': ["What Cause it: The virus is transmitted in a persistent manner by the whitefly Bemisia tabaci. Plants can also be infected via mechanical injury during field work. The virus is not passed from plant to plant in a systematic manner, nor is it seed- or pollen-borne. tomato usually get infected when volunteer plants or host weeds are present in the field. The virus multiplies in the transport tissues of plants, which explains why veins are affected first. The appearance of visible symptoms and their severity is favored by elevated temperatures around 28°C. Cooler conditions (around 22°C) may delay the multiplication of the virus and the development of symptoms.","Organic Control: Application of leaf extracts of Iresine herbstii (Herbst's bloodleaf) and Phytolacca thyrsiflora can partly inhibit virus infection and results in less incidence in the field. Extracts of the beneficial fungus Beauveria bassiana have insecticide properties against the adults, eggs and nymphs of bemisia tabaci.","Chemical Control: Always consider an integrated approach with preventive measures together with biological treatments available. Chemical control of viral infections is not possible. As for the control of whiteflies, very few treatments are effective."],
             'Tomato___healthy': "Healthy Plant",
             'Not in our predict list': "Not in our predict list, Please check the predict list before upload"  }
    prediction_name = label[pred]
    
    if len(fertilizer[prediction_name]) == 3:
        cause,org,chem = fertilizer[prediction_name][0],fertilizer[prediction_name][1],fertilizer[prediction_name][2]
    else:
        cause, org, chem = fertilizer[prediction_name], "Organic control: No need", "Chemical Control: No need"
    
    return flask.render_template('index.html', result=prediction_name, cause = cause,org=org,chem=chem,image=full_filename)



if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
